Config = {
	Server_Name = "Dusty's FiveM Server",
	Discord_Link = 'http://discord.dustydev.xyz',
	Website_Link = 'https://store.dustydev.xyz/',
	roleList = {
		{, "group.civilian"},
		{, "group.faa"},
		{, "group.safd"},
		{, "group.lspd"},
		{, "group.sasp"}, 
		{, "group.bcso"}, 
        {, "group.dispatch"}, 
        {, "group.donator"},
        {, "group.silvervip"},
		{, "group.goldvip"},
		{, "group.platvip"},
		{, "group.staff"}, 
		{, "group.trial-moderator"}, 
        {, "group.moderator"}, 
        {, "group.senior-moderator"},
		{, "group.administrator"},
		{, "group.senior-admin"},
		{, "group.head-admin"},
        {, "group.developer"},
		{, "group.management"}, 
		{, "group.co-owner"}, 
        {, "group.owner"}, 
	},
}